import sharp from "sharp"
import { readdir, writeFile } from "node:fs/promises"
import { join } from "node:path"

const GALLERY_DIR = join(import.meta.dirname, "../public/gallery")
const OUTPUT_FILE = join(import.meta.dirname, "../lib/gallery-blur.ts")

async function generateBlurDataURL(imagePath: string): Promise<string> {
  const buffer = await sharp(imagePath)
    .resize(10, 15, { fit: "cover" })
    .blur(2)
    .jpeg({ quality: 40 })
    .toBuffer()

  return `data:image/jpeg;base64,${buffer.toString("base64")}`
}

async function main() {
  try {
    const files = await readdir(GALLERY_DIR)
    const imageFiles = files.filter((f) =>
      /\.(jpg|jpeg|png|webp)$/i.test(f)
    ).sort()

    if (imageFiles.length === 0) {
      console.log("❌ Nenhuma imagem encontrada em public/gallery/")
      console.log("   Adicione imagens: 01.jpg, 02.jpg, ..., 08.jpg")
      return
    }

    console.log(`📸 Processando ${imageFiles.length} imagens...`)

    const blurData: Record<string, string> = {}

    for (const file of imageFiles) {
      const imagePath = join(GALLERY_DIR, file)
      const blurDataURL = await generateBlurDataURL(imagePath)
      const key = `/gallery/${file}`
      blurData[key] = blurDataURL
      console.log(`   ✓ ${file}`)
    }

    const output = `// Auto-generated by scripts/generate-blur.ts
// Run: bun run scripts/generate-blur.ts

export const galleryBlurData: Record<string, string> = ${JSON.stringify(blurData, null, 2)}

export function getBlurDataURL(src: string): string {
  return galleryBlurData[src] ?? "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAAIAAoDASIAAhEBAxEB/8QAFgABAQEAAAAAAAAAAAAAAAAAAAUH/8QAIhAAAgEDAwUBAAAAAAAAAAAAAQIDAAQRBRIhBhMiMUFR/8QAFQEBAQAAAAAAAAAAAAAAAAAAAAX/xAAZEQACAwEAAAAAAAAAAAAAAAABAgADESH/2gAMAwEAAhEDEEA/AKei6nquoXl1DqsijsOFVT8Y+nPuoTt8ApSiqqRZc7Kxn//Z"
}
`

    await writeFile(OUTPUT_FILE, output)
    console.log(`\n✅ Gerado: lib/gallery-blur.ts`)
    console.log(`   Importe no bento-gallery.tsx`)
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") {
      console.log("❌ Pasta public/gallery/ não encontrada")
      console.log("   Crie a pasta e adicione suas imagens")
    } else {
      throw error
    }
  }
}

main()
